### ISSUE TITLE
fx down '*' does not work

### ISSUE THREAD

**Issue by metrue** [metrue/fx#104]
`fx donw '*'` to down alll deployed functions does not work, I think we have not handle this request well now.

**Comment by metrue** [comment]
@muka 

I checkout to your PR and test, but not succeed. 


![1513423927887](https://user-images.githubusercontent.com/1001246/34070009-d53bd024-e297-11e7-81e6-be24b59d7538.jpg)


I can down multiple services with IDs `fx down id1 id2 id3 ...`,  but when I want to down them all in one command `fx down '*'`, fx client got hung.

I checked, there is not logic to handle when fx client send a '*' as down message. so maybe we need to add that.

**Comment by muka** [comment]
Hi @metrue 
the logic was in `handlers/list.go` but probably did make much sense, so I moved it to apply only to the `down` call, see https://github.com/muka/fx/blob/fixalldown/api/service/down.go#L28

I had the hung once when no functions where avail, do you have another use case to reproduce?

**Comment by metrue** [comment]
@muka 

Yes, I pull the latest code your PR, `fx down '*'` will down all the containers perfectly, but the output message seems like not correct.
![1513444338414](https://user-images.githubusercontent.com/1001246/34072780-54dc0b48-e2c8-11e7-8da3-cde6d20d8447.jpg)

you can seen, I was trying to down four services, but the return message only has two.  But four services all down though.

**Comment by muka** [comment]
Thanks, added f386c00  to fix the output. There is also an additional Error field in case something goes wrong in any of the multiple fxs

**Comment by muka** [comment]
Closing as PR has merged
