### ISSUE TITLE
Coverage fails on CircleCI environment

### ISSUE THREAD

**Issue by metrue** [metrue/fx#112]
```
#!/bin/bash -eo pipefail
./bin/coverage.sh
bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
ok  	github.com/metrue/fx/image	1.028s	coverage: 90.5% of statements
2017/12/16 21:06:29 build linux
Step 1/5 : FROM metrue/fx-node-base
--- FAIL: TestList (20.01s)
	list_test.go:74: Up failed: rpc error: code = Unavailable desc = transport is closing
FAIL
coverage: 42.1% of statements
FAIL	github.com/metrue/fx/api/service	20.247s
Exited with code 1
```

**Comment by muka** [comment]
I tried to workaround this by setting timeout, which doesn't work. 

A sane way may be to use a graceful stop of the grpc service. 

Wondering if the asynchronous download of the base images may cause this, eventually we may monitor the download with a channel? (If not there already)

I will try in a PR soon

**Comment by metrue** [comment]
@muka 

 after enable monitor of base images pulling task, circleci still  complains. not sure why.  I gonna disable the test for a which to green the build first.

**Comment by metrue** [comment]
fixed.
