### ISSUE TITLE
when make generate,  the package ' grpc-ecosystem/grpc-gateway/third_party/googleapis' doesnt exist

### ISSUE THREAD

**Issue by dh12306** [metrue/fx#167]
![image](https://user-images.githubusercontent.com/20471681/45206225-153eda00-b2b7-11e8-9c9d-d5d75bb61859.png)

the problem shows as the img above,some package cant be found. but make build is success~
  I have no idea how to find the package ? thanks for your help~~
@metrue

**Comment by metrue** [comment]
@dh12306 

Please run `make install-deps` to make sure dependencies ready first. you can check the `Makefile` for the detail.

**Comment by dh12306** [comment]
make install-deps has successed，I tried twice，it seems that there is no error
the successd img is here：
![image](https://user-images.githubusercontent.com/20471681/45249360-ce51f280-b351-11e8-80af-d174124e5788.png)
@metrue

**Comment by metrue** [comment]
I tried to reproduce youe issue but failed, everything is working well from my side.

is it ok to up a function by fx binary you build?

**Comment by metrue** [comment]
feel free to reopen it if you still have this issue.
