### ISSUE TITLE
Binary files should not be included in the repo

### ISSUE THREAD

**Issue by zjuchenyuan** [metrue/fx#18]
## Binary files should be provided by github release

When I `git clone` this repo, I found out the binary file `build/fx` is included in the git, which cost a lot of time to finish the clone.

Besides, after I clone it, I cannot run it, because architecture doesn't comply my system:

```
# file build/fx
build/fx: Mach-O 64-bit x86_64 executable
```

I suggest this binary file should be excluded from the repo, add this line for .gitignore

```
build/
```

And tell git to forget this file:

```
git rm --cached build/fx
```

Update README for a quicker clone:

```
git clone --depth 1 https://github.com/metrue/fx
```

**Comment by metrue** [comment]
@zjuchenyuan thanks for reporting that, @avelino fixed it already, thanks @avelino
