### ISSUE TITLE
it's take a very long time to download the resource

### ISSUE THREAD

**Issue by metrue** [metrue/fx#23]
I am thinking a better way to manage the docker base images stuff.  
@avelino any idea?

**Comment by muka** [comment]
Hi, I would suggest to build them instead of downloading. The logic is already avail for building functions.

**Comment by metrue** [comment]
@muka 

Yeah, I am thinking about, since fx will build service image on top of some basic Dockerfile an source code (all located in images/ dir),  I am think bundling these files into binary built.

do you have other idea?

**Comment by avelino** [comment]
sorry, not idea. Need debug :/

**Comment by metrue** [comment]
this  library is what we need.
https://github.com/jteeuwen/go-bindata

**Comment by metrue** [comment]
Now, fx no need to download anything now.
