### ISSUE TITLE
built-in database

### ISSUE THREAD

**Issue by metrue** [metrue/fx#259]
It would be great if `fx` has built-in database provider,

```
fx db up pg           # up a postgres database instance
fx db up mysql     # up a mysql databse instance
```

**Comment by hongkongkiwi** [comment]
Why not just use docker-compose for this? it seems to be implementing some extra functions and extra work for no purpose.

**Comment by metrue** [comment]
@hongkongkiwi 

This issue is kinda old and created for some specific reason, I think it's not in scope of `fx`, close it.
