### ISSUE TITLE
Unable to install on Arch Linux

### ISSUE THREAD

**Issue by SuddenGunter** [metrue/fx#281]
```
curl -o- https://raw.githubusercontent.com/metrue/fx/master/scripts/install.sh | bash
```
^ works fine without errros
but ```/usr/local/bin ``` is empty

OS: arch linux
docker and latest Go insalled.
Shell: zsh

**Comment by metrue** [comment]
@SuddenGunter Thanks for reporting this issue. 

Will check and update you soon.

**Comment by SuddenGunter** [comment]
@metrue mb this is issue on my side, how can I help investigate it?

**Comment by metrue** [comment]
Maybe there's a network glitch, can you try it one more time?

**Comment by metrue** [comment]
Hi, @SuddenGunter 

I'm going to close this issue, feel free to repon it if you still have issue.

**Comment by SuddenGunter** [comment]
now download works fine, but then 
```tar: fx: Cannot open: Permission denied
tar: Exiting with failure status due to previous errors
```
even running command with sudo didn't help.

**Comment by metrue** [comment]
@SuddenGunter 

Maybe `tar` act with different ways on Arch Linux, you can check if `tar` used correctly  here https://github.com/metrue/fx/blob/master/scripts/install.sh#L26

**Comment by SuddenGunter** [comment]
@metrue  not working

```
tar -xvzf fx.tar.gz --exclude=*.md -C .
zsh: no matches found: --exclude=*.md
```

fixed it with
``` 
  curl -o fx.tar.gz -L -O https://github.com/metrue/fx/releases/download/v0.7.1/fx_0.7.1_Tux_64-bit.tar.gz
   tar -xvzf fx.tar.gz -C .
   rm README.md
   rm fx.tar.gz
   sudo mv fx  /usr/local/bin ```
pay attention that mv must be done with sudo
