### ISSUE TITLE
Installation script extracts all files from release archive into /usr/local/bin

### ISSUE THREAD

**Issue by DropNib** [metrue/fx#282]
The installation script [tar command](https://github.com/metrue/fx/blob/a4d44a4fc0ce34c8a75d56d65d9791eed56369f4/scripts/install.sh#L26) extracts all file from the release archive into /usr/local/bin, regardless of file type. This has the effect that the README.md is extracted into the bin directory despite it not belonging there.

I would suggest to:

- either specifically extracting only the _fx_ binary
  - that could however be a problem in the future if the release every ships with more than one single binary
- or adding the --exclude option to the tar command for ignoring .md files for installation into /usr/local/bin
  - we could also directly exclude only the README.md, but if future archives ship with more than just that Markdown file, the option would have to be updated

**Comment by DropNib** [comment]
Addressed by #283

**Comment by metrue** [comment]
Thanks @DropNib 

Your PR https://github.com/metrue/fx/pull/283 has been merged.

> I would suggest to:

> either specifically extracting only the fx binary
that could however be a problem in the future if the release every ships with more than one single binary
or adding the --exclude option to the tar command for ignoring .md files for installation into /usr/local/bin
we could also directly exclude only the README.md, but if future archives ship with more than just that Markdown file, the option would have to be updated

To make things simple,  I think `fx` would alway keep shipped as one single binary unless there's a reason and we have to, and I think your fix is good enough for now, thanks a lot.
