### ISSUE TITLE
command line function "serve" not match the help description

### ISSUE THREAD

**Issue by DaidoujiChen** [metrue/fx#32]
Hello @metrue,

 Which one you prefer to use?

 [fx.go#L20](https://github.com/metrue/fx/blob/master/fx.go#L20)

 [fx.go#L63](https://github.com/metrue/fx/blob/master/fx.go#L63)

**Comment by metrue** [comment]
I prefer "serve"  [fx.go#L20](https://github.com/metrue/fx/blob/master/fx.go#L20)
