### ISSUE TITLE
Error go-getting the project: dependency

### ISSUE THREAD

**Issue by mbesancon** [metrue/fx#36]
The way dependencies are handled seem to cause conflict.

The versions of github.com/docker/go-connections/nat used in the project and in the docker/docker packages seem to conflict.

```
$ go get github.com/metrue/fx    
# github.com/metrue/fx/server/docker-api
go/src/github.com/metrue/fx/server/docker-api/api.go:61:15: cannot use "github.com/docker/go-connections/nat".PortSet literal (type "github.com/docker/go-connections/nat".PortSet) as type "github.com/docker/docker/vendor/github.com/docker/go-connections/nat".PortSet in field value
go/src/github.com/metrue/fx/server/docker-api/api.go:66:15: cannot use "github.com/docker/go-connections/nat".PortMap literal (type "github.com/docker/go-connections/nat".PortMap) as type "github.com/docker/docker/vendor/github.com/docker/go-connections/nat".PortMap in field value
```

**Comment by gerpsh** [comment]
You need to install [glide](https://github.com/Masterminds/glide) first.  If you still get the same error, try going to the source directory and [running the install steps](https://github.com/metrue/fx/blob/master/README.md#usage).

**Comment by jb08** [comment]
same error
<img width="1440" alt="screen shot 2017-11-16 at 1 52 05 pm" src="https://user-images.githubusercontent.com/8146460/32912887-1a079924-cad6-11e7-884c-efbd8a7c9b21.png">

then tried `make install-deps`, but that didn't change outcome

**Comment by mbesancon** [comment]
Error still there after go-getting glide.

```
go get -u github.com/Masterminds/glide
go get -u github.com/metrue/fx
...
# github.com/metrue/fx/server/docker-api
metrue/fx/server/docker-api/api.go:61:15: cannot use "github.com/docker/go-connections/nat".PortSet literal (type "github.com/docker/go-connections/nat".PortSet) as type "github.com/docker/docker/vendor/github.com/docker/go-connections/nat".PortSet in field value
metrue/fx/server/docker-api/api.go:66:15: cannot use "github.com/docker/go-connections/nat".PortMap literal (type "github.com/docker/go-connections/nat".PortMap) as type "github.com/docker/docker/vendor/github.com/docker/go-connections/nat".PortMap in field value
```

**Comment by gerpsh** [comment]
To install glide you need to run the [the install script](https://github.com/Masterminds/glide#install) or install via Homebrew if you're on Mac, `go get ...` won't do it.  The `install-deps` step in [the Makefile](https://github.com/metrue/fx/blob/master/Makefile#L4-L5) calls glide directly.  For the record, I think the glide dependency should be added to the README.

**Comment by mbesancon** [comment]
Yes that's for sure, or at least indicate that the project is not go-gettable (the go get command is used in the README)

**Comment by metrue** [comment]
@mbesancon You are right, I will update the README soon.

Please let me know if you still get error after trying following after install [glide](https://github.com/Masterminds/glide#install):
```
$  make install-deps && make build
```

**Comment by DaidoujiChen** [comment]
ref https://github.com/moby/moby/issues/29362

`go-connect` already contain in [moby project](https://github.com/docker/go-connections/issues?q=is%3Aissue+is%3Aclosed), but We can not use it directly.

`go get`  seems like just warning it. When we use glide to manage our dependency. This issue no more exist.

**Comment by metrue** [comment]
Hi, @DaidoujiChen 

@avelino suggests me use `dep` to do the dependency management, and I think it's a great option.

I am thinking switching to `dep`,  but no time to do that currenttly, a Pull Request `glide to dep` is big welcome. @DaidoujiChen

**Comment by mbesancon** [comment]
@metrue the 
clone + `make install-deps` works, but not `make build` which yields the same problem as go get:
```
$ make build   
go build -o ./build/fx fx.go
# github.com/metrue/fx/server/docker-api
../../../go/src/github.com/metrue/fx/server/docker-api/api.go:61:15: cannot use "github.com/docker/go-connections/nat".PortSet literal (type "github.com/docker/go-connections/nat".PortSet) as type "github.com/docker/docker/vendor/github.com/docker/go-connections/nat".PortSet in field value
../../../go/src/github.com/metrue/fx/server/docker-api/api.go:66:15: cannot use "github.com/docker/go-connections/nat".PortMap literal (type "github.com/docker/go-connections/nat".PortMap) as type "github.com/docker/docker/vendor/github.com/docker/go-connections/nat".PortMap in field value
Makefile:7: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by mbesancon** [comment]
Note: I just realized it could have to do with the fact that github..com/docker/docker redirects to github..com/moby/moby ?

**Comment by metrue** [comment]
@mbesancon I already replaced glide with dep to do the dependency management. and the latest [README.md](https://github.com/metrue/fx/blob/master/README.md) updated.

I think everything should have been fixed.

**Comment by jb08** [comment]
same issue:
<img width="537" alt="screen shot 2017-11-17 at 11 26 50 am" src="https://user-images.githubusercontent.com/8146460/32960376-47478692-cb8a-11e7-8969-8b4d8b0e0f5e.png">

**Comment by metrue** [comment]
@jb08 Please notice that fx is using `dep` to do the dependency management now.
Pls pull the latest code, then do the build.
you can refer to the latest  (README)[https://github.com/metrue/fx/blob/master/README.md].

**Comment by jb08** [comment]
worked, thanks. nice job!!

![screen shot 2017-11-17 at 1 25 27 pm](https://user-images.githubusercontent.com/8146460/32965038-db1ca2e8-cb9a-11e7-9824-ed791ca4ae08.png)

**Comment by mbesancon** [comment]
I can confirm the problem comes from the docker/docker. 

![image](https://user-images.githubusercontent.com/7623090/32965219-e6427036-cba3-11e7-8e4b-3f2b1fbc0fbe.png)

**Comment by metrue** [comment]
feel free to reopen this issue if you still met problem.
