### ISSUE TITLE
why not using plugin to implement golang faas?

### ISSUE THREAD

**Issue by xuebing1110** [metrue/fx#365]
One function as a docker container, it's too weight. why not using [plugin](https://godoc.org/plugin) to implement golang faas? It can implement multi functions in a process.

**Comment by metrue** [comment]
I think https://godoc.org/plugin is a totally different thing,  it's not good solutoion to build a service. A service/function as a container maybe a little weight, but we can take a lot advantage for container ecosystem on management, maintainent and scale, etc.
