### ISSUE TITLE
Should we need to remove temporary docker file / folder?

### ISSUE THREAD

**Issue by DaidoujiChen** [metrue/fx#40]
Hello @metrue,

There are a lot of temporary items in my working folder.
<img width="208" alt="2017-11-17 11 31 40" src="https://user-images.githubusercontent.com/670441/32928072-270323d6-cb8b-11e7-8fe5-fe97dc0b6cd6.png">
Is this necessary?

**Comment by metrue** [comment]
Maybe we should push these file into /var/ or somewhere.

then clean up when deploy service done.

**Comment by metrue** [comment]
fixed by @xwjdsh already.
