### ISSUE TITLE
Error in JS example

### ISSUE THREAD

**Issue by nkev** [metrue/fx#44]
In the readme, please add 's' to example in `fx up ./example/functions/func.js`.

It still doesn't work after that change:

![image](https://user-images.githubusercontent.com/5410916/32978351-9e49ab0e-cc94-11e7-91e5-88a7e26f7f2a.png)

**Comment by metrue** [comment]
@nkev 

Could you also provide the message of `fx serve` side ?

**Comment by nkev** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/5410916/32978421-2677b182-cc96-11e7-9ac9-f81722962ad4.png)

**Comment by metrue** [comment]
@nkev I see

since fx is built on top of Docker, you should have docker running before you run `fx serve`

you can refer to https://docs.docker.com/engine/installation/ about how to install Docker and run.

**Comment by nkev** [comment]
Docker is running now but still no joy (websocket error):
![image](https://user-images.githubusercontent.com/5410916/32979280-52725c28-cca6-11e7-92be-976f510c26f7.png)

**Comment by nkev** [comment]
FYI, the service is actually running correctly:

`curl -X POST 192.168.0.14:52817 -H "Content-Type: application/json" -d '{"a": 1, "b": 7}'`

...returns `8` as expected.

**Comment by metrue** [comment]
@nkev Great，hope you like fx.

I will open another issue about that websocket error.
