### ISSUE TITLE
Machine Readable list command

### ISSUE THREAD

**Issue by hongkongkiwi** [metrue/fx#461]
Hi there, 

I plan to use hooks for handling service deployment, but in the meantime is it possible to add a simple json output to the list command, that way I can process the results and know what services are deployed along with name, port and ID, this will help in automation with gitlab that I'm working on.

**Comment by metrue** [comment]
@hongkongkiwi 

It'd be a small enhancement, the related code is here https://github.com/metrue/fx/blob/master/handlers/list.go#L19 

We can add an option `--format` to `fx list`, then doing a little change in the above code,
```golang

if (format == "json") {
  output, err := json.Marshal(services)
  if err != nil {
     return err
  }
  fmt.Println(string(output))
} else {
  render.Table(services)
}
```

**Comment by metrue** [comment]
Fixed by https://github.com/metrue/fx/pull/462,  try following command to adopt the new release
```
brew upgrade metrue/fx/fx
```

feel free to re-open it as you need.
