### ISSUE TITLE
faster deployment

### ISSUE THREAD

**Issue by metrue** [metrue/fx#52]
here is the idea:
 fx can docker pull the base images of all the supported language first background, then deploy should be faster than ever.

**Comment by xwjdsh** [comment]
For me, I just need two or three base images, other supported language images are useless.

I believe this is a common problem.

**Comment by metrue** [comment]
@xwjdsh 

currently,  Pulling base images are async task, it does not block any main thread right now.
https://github.com/metrue/fx/blob/27a02c8a7476e83cefbd73a9d6205674eb21790d/server/env/env.go#L25

**Comment by xwjdsh** [comment]
Sorry for the late response, I mean, I always clean those never used images on my host.
