### ISSUE TITLE
Support request service with HTTP GET with payload in query string in Rust service.

### ISSUE THREAD

**Issue by metrue** [metrue/fx#528]
#### HTTP POST works as expect.
```shell
$ cat payload.json
{
  "a": 1,
  "b": 1
}

$ http 0.0.0.0:52857 < payload.json
HTTP/1.1 200 OK
Content-Length: 12
Content-Type: application/json
Date: Fri, 22 May 2020 04:54:44 GMT
Server: Rocket

{
    "result": 2
}
```

#### HTTP GET: 404

```shell
./build/fx up -n rust examples/functions/Rust/func.rs

 http 0.0.0.0:52857?a=1&b=1
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <title>404 Not Found</title>
            </head>
            <body align="center">
                <div align="center">
                    <h1>404: Not Found</h1>
                    <p>The requested resource could not be found.</p>
                    <hr />
                    <small>Rocket</small>
                </div>
            </body>
            </html>
```

### Expect
```shell
curl  curl 0.0.0.0:57089?a=1&b=1

HTTP/1.1 200 OK
Content-Length: 12
Content-Type: application/json
Date: Fri, 22 May 2020 04:54:44 GMT
Server: Rocket

{
    "result": 2
}
```

**Comment by metrue** [comment]
@FrontMage 

Since you are the original commitor of Rust function support,  do you some inputs for this topic?

**Comment by FrontMage** [comment]
@metrue I checked the file, there is no `GET` entrance in `main.rs`, assuming it's a bug, I will try to fix it.

**Comment by metrue** [comment]
Hi @FrontMage 

As the data used inside `function` comes from HTTP request query or request body, normally, the **GET** maybe append query,  and **POST** attached with body (there is no restriction in definition in [spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html))
```
METHOD      BODY
--------------------------------
GET         NO
POST        YES
PUT         YES
PATCH       YES
DELETE      NO
```

So I think support **GET** (fetch data from request.query) and **POST** (fetch data from request.body) should be enough for now.

**Comment by FrontMage** [comment]
@metrue I was working on this last night, unfortunately, the upstream library `Rocket` might have a bug related to query string parse, I filed an issue to the upstream, meanwhile, I will try to implement the trait by myself, it will take some time.

**Comment by metrue** [comment]
@FrontMage 

Thanks so much for the updates, take your time and let me know if anything I can help.

**Comment by FrontMage** [comment]
@metrue Thanks, I do have a question though, my branch was checked out from `support-R` ages ago, I'm afraid merging to master would be a huge problem, is there a contribution guide I can read?

**Comment by metrue** [comment]
@FrontMage 

The contribution guide is ongoing, but I can give a quick solution here.
```
git clone https://github.com/metrue/fx
git checkout master
cd assets/dockerfiles/base/rust
# do some change as you want
docker build -t fx_rust .
```
after you make sure that we can run this image and accept **GET** and **POST**, you can submit your PR then.

Let me know if you have more questions.
