### ISSUE TITLE
How to load require images?

### ISSUE THREAD

**Issue by xwjdsh** [metrue/fx#60]
The link `https://raw.githubusercontent.com/metrue/fx/master/images.zip` response 404.

**Comment by metrue** [comment]
@xwjdsh fixed. Please try again.

**Comment by xwjdsh** [comment]
It's ok now, thanks.

**Comment by metrue** [comment]
2017-11-21 14:45 GMT+08:00 Wendell Sun <notifications@github.com>:
> The link https://raw.githubusercontent.com/metrue/fx/master/images.zip response 404.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



-- 
Sincerely, 

********************************************
www.minghe.me
********************************************
