### ISSUE TITLE
external modules (npm packages)

### ISSUE THREAD

**Issue by akhil-naidu** [metrue/fx#624]
I would like to use external npm packages while writing my functions, like `axios`. How can I do this?

**Comment by metrue** [comment]
Hi @akhil-naidu 
You can do it with before build `hooks`, for example, you define your API in `./api` directory, then your project structure may look like this.
```
✗ tree -a api
api
├── .hooks
│   └── before_build
└── func.js
```

and inside the `before_build` file,  you can install npm package inside it.
```
npm install axios
```

Then you can just use the package inside your function, please notice that fx run with JavaScript function with Node v16.3.0 current.  a minimal example can be like
```javascript
const axios = require('axios')

const fx = (ctx) => {
  axios
    .get('https://google.com')
    .then(() => {
      ctx.body = `ok`
    })
    .catch((error) => {
      ctx.body = `${error}`
    })
}

module.exports = fx
```

**Comment by akhil-naidu** [comment]
I'm using the latest node and will go through your suggestions. 

> Once done I will update the status accordingly.

**Comment by akhil-naidu** [comment]
While following you above instructions, I'm facing few issues. So, I would like to elaborate on my issue so that you can have a better perspective.

## Pre Configuration

1. Created a new digital ocean droplet with one-click docker installation  => `Docker version 20.10.7, build f0df350`
2. Installed nvm-sh for installing node => `v16.9.1`
3. Installed fx via the bash script mentioned in the repo => `fx version 0.9.48`

> Now, I have all the required installations, so I started setting up things. 

## The error I'm facing while following the instructions

```
root@ubuntu:~/functions# fx up --name func func.js 
Starting building
/tmp/fx-hook-script-624645303: 1: /root/functions/.hooks/before_build: Permission denied
1 / 100 [>_________________________________________________________] 1.00% ? p/s
building: ✗
*****************
exit status 126
*****************
```
> For more info, I'm also adding my directory structure for a quick overview.

```
root@ubuntu:~# tree -a functions -L 4
functions
├── .hooks
│   └── before_build
│       ├── node_modules
│       │   ├── .package-lock.json
│       │   ├── axios
│       │   └── follow-redirects
│       ├── package-lock.json
│       └── package.json
└── func.js

5 directories, 4 files
```

**Comment by metrue** [comment]
@akhil-naidu Sure, feel free to re-open this issue when you want.
