### ISSUE TITLE
How to add 3rd-party modules

### ISSUE THREAD

**Issue by KenMercusLai** [metrue/fx#629]
I'm trying to add 3rd-party modules into my functions, like netmiko, which results in error:
Starting deploying hello
86 / 100 [------------------------------------------------------------------------------------------------------------------------------------------------------------->_________________________] 86.00% 21 p/s
deploying hello: ✗
*****************
container start failure: ☺- * Serving Flask app 'app.py' (lazy loading)
☺nvironment: production
☺T   WARNING: This is a development server. Do not use it in a production deployment.
☺)   Use a production WSGI server instead.
☺‼ * Debug mode: off
☻sage: flask run [OPTIONS]
☻!Try 'flask run --help' for help.
☻☺
☻9Error: While importing 'app', an ImportError was raised:
☻☺
☻#Traceback (most recent call last):
☻V  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 256, in locate_app
☻∟    __import__(module_name)
☻&  File "/app.py", line 1, in <module>
☻▬    from fx import fx
☻%  File "/fx.py", line 1, in <module>
☻‼    import netmiko
☻/ModuleNotFoundError: No module named 'netmiko'
☻☺

*****************
PS C:\Users\laik\PycharmProjects\fx\examples\functions\Python>

How can I define which module should be added during building the container?

**Comment by metrue** [comment]
Hi @KenMercusLai 

You can check this closed issue https://github.com/metrue/fx/issues/624, let me know if you need more help.

**Comment by KenMercusLai** [comment]
Thanks for the reply. I tried to add the .hooks folder with a before_build file in my code. 

It seems fx can't build the new image
```
PS C:\Users\laik\PycharmProjects\fx\examples\functions\Python> fx up --name hello -p 65534 func.py
Starting building
1 / 100 [->____________________________________________________________________________________________________________] 1.00% ? p/s
building: ✗
*****************
exec: "/bin/sh": file does not exist
*****************
```

I tried to launch the /bin/sh from the base image and it succeeded.
```python
PS C:\Users\laik\PycharmProjects\fx\examples\functions\Python> docker run -it --rm metrue/fx-python-base /bin/sh
#
# pip install netmiko
Collecting netmiko
  Downloading netmiko-3.4.0-py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 2.1 MB/s
Collecting pyserial
  Downloading pyserial-3.5-py2.py3-none-any.whl (90 kB)
     |████████████████████████████████| 90 kB 8.0 MB/s
Collecting ntc-templates
  Downloading ntc_templates-3.0.0-py3-none-any.whl (303 kB)
```

So I guess the base image is definitely fine, but just the building has some issues. Unfortunately, I don't know go at all.

**Comment by KenMercusLai** [comment]
Just tested on a Linux box, and turns out the before_build hook runs commands on the host. So if I want to include a 3rd-party module in my python script by using
```python
pip3 install netmiko
```

It invoked pip3 on the host and installed everything, but not in the new image.

I think this also explained why the hook failed on windows because the code of the hook uses `/bin/sh` to run scripts, which doesn't exist on Windows.

**Comment by metrue** [comment]
Hi @KenMercusLai 

You're right, the `before_build` executes on host, not in the target container (https://github.com/metrue/fx/blob/master/hook/hook.go#L57)

I knew it's so lame, but I have not got a perfect solution for dependency management for functions here, especially `fx` is supporting multiple languages which makes things complicated more.

Enabling the 3rd-party modules using inside a function running in container means the 3rd-party modules have to be built into docker image of `fx` function,  thinking of what `fx up <func.py>` does, 

1. copy `func.py` into a Docker based project which is a web service serve a single API. 
2. `docuker build` above project into a Docker image.
3. `docuker run` the container exposing ports onto host

So 3rd-party modules injection should happen before step 2,  that means the 3rd-party modules actually installation and moved to `fx` function project on host.

It's possible that the the 3rd-party modules actually installation happens inside the container, but it means the installation scription has to be inject to Dockerfile like `RUN pip3 install netmiko`, I have not  tried it yet so it's not sure if it's good solution.

**Comment by KenMercusLai** [comment]
Thanks for the reply and explanation. Anyway, I think the project has given me a good hint of how to implement a serverless backend.

**Comment by UmutAlihan** [comment]
Hi,

Is there any progress on injecting 3rd party packages into python function?
