### ISSUE TITLE
Support D Language

### ISSUE THREAD

**Issue by metrue** [metrue/fx#96]
* how support more language

**Comment by andre2007** [comment]
I started to implement the support for the D Programming Language but currently facing some issues due to the lack of knowledge.

- Is it sufficient to create the docker files in fx\assets\dockerfiles\...? Or do I have to publish them to the docker repo or do I have to execute any other docker command after creating these files?

- Do I have to add the assets/dockerfiles/fx/d/* manually to the list in file asset.go?

- How do I regenerate the asset.go file? I executed the go-bindata command and the size of the asset.go file decreased from 10MB to 200kb

- While executing fx up func.d there is following exception thrown:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x67278d]

goroutine 23 [running]:
archive/tar.(*Writer).Close(0x0, 0xc042302660, 0xc042302600)
        C:/Go/src/archive/tar/writer.go:353 +0x2d
github.com/fx/vendor/github.com/jhoonb/archivex.(*TarFile).Close(0xc042302600, 0xc0422a6140, 0x37)
        C:/Users/pc/go/src/github.com/fx/vendor/github.com/jhoonb/archivex/archivex.go:379 +0x39
github.com/fx/vendor/github.com/metrue/fx/docker-api.Build(0xc0423162a0, 0x14, 0xc0422a6140, 0x37)
        C:/Users/pc/go/src/github.com/fx/vendor/github.com/metrue/fx/docker-api/api.go:40 +0xba
github.com/fx/vendor/github.com/metrue/fx/handlers.Up(0x0, 0x0, 0xc0423140e8, 0x6, 0xc04231e090, 0x2d, 0xc0422a84e0)
        C:/Users/pc/go/src/github.com/fx/vendor/github.com/metrue/fx/handlers/up.go:56 +0x200
created by github.com/fx/vendor/github.com/metrue/fx/server.up
        C:/Users/pc/go/src/github.com/fx/vendor/github.com/metrue/fx/server/server.go:45 +0x2d6
```
What could be the reason for this exception?

**Comment by metrue** [comment]
@andre2007 

You can create a PR first, then I check why it does not work as expect with you.

**Comment by andre2007** [comment]
Due to the fx entry in .gitignore the files in folder assets/dockerfiles/fx/d won't be included in the pull request. How should I handle this?

**Comment by muka** [comment]
I think `fx` in .gitignore should be `/fx`. Do you agree @metrue ?

**Comment by metrue** [comment]
@muka yes.

@andre2007 I already updated it, go ahead file a PR.

**Comment by andre2007** [comment]
I will create a pull request.  With the newest version I cannot execute 
``
`make install-deps && make build
```
gen.sh: line 6: protoc: command not found
gen.sh: line 9: protoc: command not found
gen.sh: line 16: protoc: command not found
gen.sh: line 23: protoc: command not found
api\fx.go:1: running "sh": exit status 127
make: *** [generate] Fehler 1

I am not sure but the gen.sh script looks like fx can only be built on linux and not on windows 10?

**Comment by muka** [comment]
Hi @andre2007 
my fault.. I think this can be addressed in #102 

In the meanwhile you can avoid to run the `make generate` (from `build` in Makefile). It will generate code that is  already available in the repository and should not impact the build command

**Comment by metrue** [comment]
@andre2007 

I know there is still some block issues frustrate you, but you still can  PR your change if you like, then we can check it together to make it forward.

**Comment by andre2007** [comment]
Frustration is the normal work environment of software developers:). With the developer of a dependency I clarified some technical and license questions. I hope to create a pull request of a raw version next few days.

**Comment by andre2007** [comment]
Pull request #105 created

**Comment by andre2007** [comment]
Unfortunately make install-deps && make build is still failing on Windows platform:

```
$ make install-deps && make build
# install protoc
./bin/install_protoc.sh
Sorry, this script on works on Linux/Mac now
# install protobuf and grpc
go get -u github.com/golang/protobuf/protoc-gen-go
go get -u github.com/golang/protobuf/protoc-gen-go
go get -u google.golang.org/grpc
go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
git clone --depth 1 https://github.com/googleapis/googleapis.git vendor/github.com/googleapis
Cloning into 'vendor/github.com/googleapis'...
remote: Counting objects: 564, done.
remote: Compressing objects: 100% (457/457), done.
remote: Total 564 (delta 147), reused 246 (delta 66), pack-reused 0
Receiving objects: 100% (564/564), 641.51 KiB | 86.00 KiB/s, done.
Resolving deltas: 100% (147/147), done.
Checking connectivity... done.
cp -rf vendor/github.com/googleapis/google/ api/google/
# install the other dependencies
dep: WARNING: branch, version, revision, or source should be provided for "github.com/docker/docker"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/docker/go-connections"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/gorilla/websocket"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/jhoonb/archivex"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/metrue/fx"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/phayes/freeport"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/rs/xid"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/golang/protobuf"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/grpc-ecosystem/grpc-gateway"
go generate ./api/fx.go
gen.sh: line 11: /c/Users/pc/go/src/github.com/fx/vendor/protoc/bin/protoc: No such file or directory
gen.sh: line 18: /c/Users/pc/go/src/github.com/fx/vendor/protoc/bin/protoc: No such file or directory
gen.sh: line 27: /c/Users/pc/go/src/github.com/fx/vendor/protoc/bin/protoc: No such file or directory
gen.sh: line 36: /c/Users/pc/go/src/github.com/fx/vendor/protoc/bin/protoc: No such file or directory
api\fx.go:1: running "sh": exit status 127
make: *** [generate] Fehler 1
```

**Comment by andre2007** [comment]
The docker command in NEW_LANGUAGE_SUPPORT.md seems to be wrong. 
```docker -t <foo-bar> build .``` causes an error: unknown shorthand flag: 't' in -t
The syntax which works for me: ```docker build -t <foo-bar> .```

**Comment by andre2007** [comment]
You might also enhance the docker run command in NEW_LANGUAGE_SUPPORT.md with the port information. It seems without specifying the port, you cannot test it:
```docker run -p 3000:3000 <foo-bar>```

**Comment by metrue** [comment]
@andre2007 
Yes, I updated that doc already. https://github.com/metrue/fx/commit/3128421b6b18834ad198385233dc327db36ab3f9

**Comment by metrue** [comment]
closed since we made it.
